### ISSUE TITLE
The CAD designs aren't open

### ISSUE THREAD

**Issue by ukd1** [oxplot/splapr#1]
I stumbled on this after reading about your STUSB4500 project - but noticed the CAD files aren't open and I can't access them with the link (I was asked to sign up to a professional plan trial).

Any chance you can put the CAD on GitHub?

**Comment by ukd1** [comment]
p.s. super cool project

**Comment by oxplot** [comment]
You can sign up for a free account (which is what I use). Nonetheless, I'll export the most recent version and put it in the repo for easier access. Thanks for the feedback.

**Comment by ukd1** [comment]
@oxplot thanks!
